#!/bin/bash

docker-compose up -d mysql
docker-compose run db_client schema

docker-compose run maven mvn --quiet -f /tmp clean install

docker-compose run db_client demo
docker-compose run maven java -jar /tmp/target/test-containers-1.0-SNAPSHOT-jar-with-dependencies.jar
docker-compose down --remove-orphans