name: test-containers-CI
on: push
permissions:
  contents: read
jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: CI
#        run: script/ci
#      - name: DEMO
#        run: script/demo
      - name: SEC_RES
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mysql:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-docker.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-docker.sarif'

