name: test-containers-CI
on: push
permissions:
  contents: read
jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: CI
#        run: script/ci
#      - name: DEMO
#        run: script/demo
      - name: SEC_RES
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: 'mysql:latest'
          ignore-unfixed: true
          vuln-type: "os,library"
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
#          template: '@/contrib/sarif.tpl'
#          output: 'trivy-results.sarif'
#
#      - name: Upload Trivy scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: 'trivy-results.sarif'